version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "15432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: access_key_manager_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kmnetwork

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/access_key_manager_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - kmnetwork

volumes:
  postgres-data:

networks:
  kmnetwork:
    name: kmnetwork
    external: true
