
name: Build and Deploy
on:
  push:
    branches:
      - dev  # Adjust the branch name as needed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Install Maven
      - name: Install Maven
        run: sudo apt-get install -y maven
      # Step 3: Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Step 4: Check directory contents
      - name: Check directory contents
        run: ls -la
      # Step 5: Build the Maven project
      - name: Build with Maven
        run: mvn clean package -DskipTests
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Install SSH key to access EC2 instance securely
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Step 2: SSH into EC2 instance and deploy application
      - name: SSH into EC2 instance and deploy
        run: |
          # SSH into the EC2 instance using the provided SSH key and EC2 public IP
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'cd AccessKeyManager/ &&
          # Pull the latest changes from the Git repository
          git pull &&
          # Build and run Docker containers using Docker Compose
          docker-compose up -d'
